name: tarea7.yml
on: [push]

jobs:
  buid-node:
    runs-on: ubuntu-latest
    container: mongo
    steps:
      - run: echo "Running inside Container"
      - run: |
          mongosh --eval "db.runCommand({ ping: 1 })"
